### ISSUE TITLE
Not working "out of the box"

### ISSUE THREAD

**Issue by caballerofelipe** [rodolphebarbanneau/python-docstring-highlighter#5] opened 2024-05-23 22:08 UTC
I just installed it but it's not working. Do I need to press some key combo or something? I didn't see any mentions to this. I might be doing something wrong...

I do have the Microsoft Python Extension (v2024.6.0).

**Comment by rodolphebarbanneau** [comment] 2024-05-28 13:07
Hello, it should work out of the box! However, some custom theming might conflict with the colors.

Please check #1, where I explain how to analyze if the extension is working as intended and how to customize the settings:

---

- Run the VSCode command `Developer - Inspect Editor Tokens and Scopes` (using `Cmd`+`Shift`+`P`)
- Left click on a character in your source to inspect the available scopes (you can enable/disable the extension to see which scopes it adds to the source code, see [Available Scopes](https://github.com/rodolphebarbanneau/python-docstring-highlighter?tab=readme-ov-file#available-scopes) :

![Screenshot 2024-03-17 at 20 36 34](https://github.com/rodolphebarbanneau/python-docstring-highlighter/assets/46493454/3bcc99ff-b407-465b-a739-a3275b507fa1)

As you can see, the extension adds a bunch of scopes and VSCode will look up for the first scope that implements a style. In my example, it's the `punctuation.definition.tag` style that is used (standard scope as I don't have custom theming). You can override this behavior by adding this in you `settings.json` file for instance:

```json
"editor.tokenColorCustomizations": {
  "textMateRules": [
    {
      "scope": "docstring.variable",
      "settings": {
        "fontStyle": "bold underline",
        "foreground": "#569cd6",
      }
    },
  ]
}
```

Then you can play around to make it as you like!

_Originally posted by @rodolphebarbanneau in https://github.com/rodolphebarbanneau/python-docstring-highlighter/issues/1#issuecomment-2002595456_

**Comment by caballerofelipe** [comment] 2024-06-03 00:09
Thanks!

I was using the theme "Light (Visual Studio) Visual Studio Light" and it wasn't showing the formatting. I changed it and now I see everything.

However, if I add the settings you posted they work and I am able to see the change in color, underlined and in bold. So I guess there's some incompatibility with that theme directly as you said.

**Comment by rodolphebarbanneau** [comment] 2024-07-11 11:05
Thanks for the feedback, glad it works for you!
If there are no further issues, I'll close this ticket.

**Closed by rodolphebarbanneau** 2024-07-11 11:05 UTC
Labels: help wanted
